### ISSUE TITLE
Ravencoin app freezes with firmware v1.6 beta

### ISSUE THREAD

**Issue by Scotty0448** [Kryptoxic/ledger-app-rvn#1]
Ledger is about to release firmware v1.6.0.  I've installed the beta of that version and have found that the device freezes upon attempting to open the current Ravencoin app v1.3.13.  Perhaps the app needs to be brought up-to-date with the latest BTC app, which is v1.3.16.

**Comment by Kryptoxic** [comment]
Ledger just released the code for 1.3.16. I will update the app and push a new release asap. Hang tight

**Comment by Kryptoxic** [comment]
App has been updated. Bug discovered with wallet freezing when trying to sign transaction. Suspect that it may be due to wallet. Closing issue for the time being.
